config/routes.rb
Rails.application.routes.draw do
  resources :years do
    resources :people, :finishes
    resource :activity
    get "reports" => "reports#index"
    get "reports/:action", controller: :reports
  end

  resources :reports, only: :index
  get "reports/:action/:race_id", controller: :reports

  get ":year_id/:distance/:action", controller: :reports, as: :year_report

  # root 'finishes#index', year_id: Time.now.year
  root "reports#index", homepage: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_filter :find_year
  before_filter :find_race, only: [:results, :numbers, :age_groups]

  def index
    @page_title = "Pickford Hay Days - Race Results"
    render layout: "application"
  end

  def results
    @page_title = "Pickford Hay Days - #{@race.year} #{@race.name} Results"
    # @people = @race.people.order("finishes.time IS NOT NULL, finishes.place").includes(:finishes)
    @finished = @race.people.where("finishes.time IS NOT NULL AND finishes.place IS NOT NULL").order("finishes.place").includes(:finishes)
    @not_finished = @race.people - @finished

    respond_to do |format|
      format.html
      format.txt
    end
  end

  def numbers
    @people = @race.people.order("number")
  end

  def age_groups
    @page_title = "Pickford Hay Days - #{@race.year} #{@race.name} Age Group Results"
    @age_groups = @race.age_groups.order("low, high, gender_id")
  end

  def map
    @race = Race.find :first
    @people = Person.all
  end

  def mailing
    year = Year.find_by_year(params[:id])
    @races = year.races.where("distance > 2").includes({people: :gender})
    respond_to do |format|
      format.html { render layout: false }
      format.csv do
        render type: "text/csv; charset=utf8; header=present",
               disposition: %(attachment; filename="mailing_list.csv")
      end
    end
  end

  private

  def find_race
    year = Year.find_by!(year: params[:year_id])
    @race = Race.find_by!(year: year, distance: params[:distance].to_i)
  end
end

app/views/reports/age_groups.html.erb
<% Gender.all.each do |gender| -%>
  <h2><%=h @race.name %> Overall <%=h gender.name %></h2>

	<table>
		<thead>
			<tr>
				<th>Overall Place</th>
				<th>Time</th>
				<th>Name</th>
				<th>Hometown</th>
				<th>Age</th>
				<th> </th>
			</tr>
		</thead>
		<tbody>
	<% @race.overall_winners_for_gender(gender).each do |person| -%>
	  <tr>
			<td class="right"><%=h person.place(@race) unless person.finishes.for_race(@race).empty? %></td>
			<td class="right"><%=h person.time(@race) unless person.finishes.for_race(@race).empty? %></td>
  		<td><%=h person.name %></td>
  		<td><%=h person.hometown %></td>
  		<td class="right"><%=h person.age %></td>
  		<td><%=h person.readable_place_in_age_group(@race) %></td>
  	</tr>
	<% end -%>
	</tbody>
	</table>

<% end -%>

<% @age_groups.each do |group| -%>
	<% unless group.people.finished.empty? %>
		<h2><%=h group.name %></h2>

		<table>
			<thead>
				<tr>
					<th>Overall Place</th>
					<th>Time</th>
					<th>Name</th>
					<th>Hometown</th>
					<th>Age</th>
					<th> </th>
				</tr>
			</thead>
			<tbody>
		<% group.people.finished.each do |person| -%>
		  <% unless @race.overall_winners_for_gender(person.gender).include?(person) %>
		  <tr>
  			<td class="right"><%=h person.place(@race) unless person.finishes.for_race(@race).empty? %></td>
  			<td class="right"><%=h person.time(@race) unless person.finishes.for_race(@race).empty? %></td>
  			<td><%=h person.name %></td>
  			<td><%=h person.hometown %></td>
  			<td class="right"><%=h person.age %></td>
  			<td><%=h person.readable_place_in_age_group(@race) %></td>
  		</tr>
  		<% end -%>
  	<% end -%>
		</tbody>
		</table>

	<% end -%>
<% end -%>

app/views/reports/index.html.erb
<h1>Race Results</h1>

<% Year.order("year DESC").each do |year| %>
  <h2><%= year %></h2>
  <p>
    <%= pluralize year.people.count, 'runner' %> from <%= year.people.map(&:state).uniq.size %> states/provences.
  </p>

  <table>
    <tr>
      <% reports = params[:public] ? %w(numbers results age_groups) : %w(results age_groups) %>
      <% reports.each do |report| %>
        <td style="padding-right: 2em">
          <h3><%= report.humanize %></h3>

          <% year.races.each do |race| %>
            <%= link_to race, year_report_path(action: report, distance: race.short_name, year_id: year.year) %><br>
          <% end %>

        </td>
      <% end %>
    </tr>
  </table>

  <hr>
<% end %>

app/views/reports/mailing.csv.erb
<%= %w(name age gender street city state zip race).join(',') %>
<%- @races.map(&:people).flatten.each do |person| -%>
<%= [person.name, person.age, person.gender, person.street, person.city, person.state, person.zip, person.race].map{|x| "\"#{x.to_s.gsub('"', '""')}\""}.join(',') %>
<%- end -%>

app/views/reports/mailing.html.erb
<h1>People as hCards</h1>

<p><%= link_to 'download .vcf', "http://h2vx.com/vcf/#{controller.request.url}"%></p>

<ul>
  <%- @races.map(&:people).flatten.each do |person| -%>
  <li class="vcard">
    <span class="fn"><%=h person.name %></span><br />
    <div class="adr">
      <div class="street-address"><%=h person.street %></div>
      <span class="locality"><%=h person.city %></span>,  
      <span class="region"><%=h person.state %></span>  
      <span class="postal-code"><%=h person.zip %></span>
      <div class="country-name"><%=h person.country %></div>
    </div>
    <span class="note">
      <%- person.races.each do |race| -%>
        <%=h race.year %> - <%=h race %>
      <%- end -%>
    </span>
  </li>
  <%- end -%>
</ul>

app/views/reports/map.html.erb
<% @map = true -%>
<div id="map" style="height: 600px"></div>

app/views/reports/numbers.html.erb
<table>
	<thead>
		<tr>
			<th>Number</th>
			<th>Name</th>
			<th>Hometown</th>
			<th>Age</th>
			<th>Age Group</th>
		</tr>
	</thead>
	<tbody>
<% @people.each do |person| -%>
<tr>
	<td class="right"><%=h person.number %></td>
	<td><%=h person.name %></td>
	<td><%=h person.hometown %></td>
	<td><%=h person.age %></td>
	<td><%=h person.age_group(@race).name %></td>
</tr>	
<% end -%>
</tbody>
</table>

app/views/reports/race.html.erb
<table>
	<thead>
		<tr>
			<th>Place</th>
			<th>Time</th>
			<th>Name</th>
			<th>Hometown</th>
			<th> </th>
		</tr>
	</thead>
	<tbody>
<% @finished.each do |person| -%>
<tr>
	<td class="right"><%=h person.place(@race) unless person.finishes.for_race(@race).empty? %></td>
	<td class="right"><%=h person.time(@race) unless person.finishes.for_race(@race).empty? %></td>
	<td><%=h person.name %></td>
	<td><%=h person.hometown %></td>
	<td><%=h person.readable_place_in_age_group(@race) %></td>
</tr>
<% end -%>

<% @not_finished.each do |person| -%>
<tr>
	<td class="right">TBD</td>
	<td class="right"></td>
	<td><%=h person.name %></td>
	<td><%=h person.hometown %></td>
	<td><%=h person.readable_place_in_age_group(@race) %></td>
</tr>
<% end -%>
</tbody>
</table>

app/views/reports/race.txt.erb
<%- @people.each do |person| -%>
<%=h person.name %>, <%=h person.age %>, <%=h person.hometown %>, <%=h person.time(@race) unless person.finishes.for_race(@race).empty? %>
<%- end -%>

app/views/reports/results.html.erb
<table>
	<thead>
		<tr>
			<th>Place</th>
			<th>Time</th>
			<th>Name</th>
			<th>Hometown</th>
			<th> </th>
		</tr>
	</thead>
	<tbody>
<% @finished.each do |person| -%>
<tr>
	<td class="right"><%=h person.place(@race) unless person.finishes.for_race(@race).empty? %></td>
	<td class="right"><%=h person.time(@race) unless person.finishes.for_race(@race).empty? %></td>
	<td><%=h person.name %></td>
	<td><%=h person.hometown %></td>
	<td><%=h person.readable_place_in_age_group(@race) %></td>
</tr>
<% end -%>

<% @not_finished.each do |person| -%>
<tr>
	<td class="right">TBD</td>
	<td class="right"></td>
	<td><%=h person.name %></td>
	<td><%=h person.hometown %></td>
	<td><%=h person.readable_place_in_age_group(@race) %></td>
</tr>
<% end -%>
</tbody>
</table>

app/views/reports/results.txt.erb
<%- @people.each do |person| -%>
<%=h person.name %>, <%=h person.age %>, <%=h person.hometown %>, <%=h person.time(@race) unless person.finishes.for_race(@race).empty? %>
<%- end -%>