config/routes.rb
Rails.application.routes.draw do
  resources :years do
    resources :people, :finishes
    resource :activity
    get "reports" => "reports#index"
    get "reports/:action", controller: :reports
  end

  resources :reports, only: :index
  get "reports/:action/:race_id", controller: :reports

  get ":year_id/:distance/:action", controller: :reports, as: :year_report

  # root 'finishes#index', year_id: Time.now.year
  root "reports#index", homepage: true
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "#{controller.controller_name}: #{controller.action_name}" %></title>
  <%= stylesheet_link_tag 'scaffold', 'main' %>
  <%= stylesheet_link_tag 'iphone', :media => 'only screen and (max-device-width: 480px)' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless controller.controller_name == "reports" %>
  <nav>
    <%= link_to_unless_current "Registration", year_people_path(@year || Year.order(year: :desc).first) %> |
    <%= link_to_unless_current "Finish Line", year_finishes_path(@year || Year.order(year: :desc).first) %> |
    <%= link_to_unless_current "Reports", reports_path %>
  </nav>
<% end %>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/layouts/reports.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || controller.action_name %></title>
  <%= stylesheet_link_tag 'reports', :media => 'all' %>
  <%#= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'mapstraction/mapstraction' if @map %>
  <%- if params[:refresh] -%>
    <script>
      // Sad hack for refreshing content
      setTimeout("window.location.reload( false );", 5000);
    </script>
  <%- end -%>
  <% if @map -%>
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<%= GOOGLE_MAPS_API_KEY %>" type="text/javascript"></script>

    <script type="text/javascript">
      function loadLocationMap(map) {
        var points = [];
        var markers = [];
        <% @people.select(&:geocode).each_with_index do |person, index| %>
          // create a lat/lon object
          points[<%= index %>] = new LatLonPoint(<%= person.geocode.latitude %>, <%= person.geocode.longitude %>);
          // display the map centered on a latitude and longitude (Google zoom levels)
          <% if index == 0 %>map.setCenterAndZoom(points[0], 4);<% end %>

          // create a marker positioned at a lat/lon
          markers[<%= index %>] = new Marker(points[<%= index %>]);
          // add info bubble to the marker
          markers[<%= index %>].setInfoBubble("<%=h person.name %><br /><%=h person.city %>");

          // display marker
          map.addMarker(markers[<%= index %>]);
        <% end %>

      }


      Event.observe(window, 'load', function() {

        var mapstraction = new Mapstraction('map','google');
        loadLocationMap(mapstraction);
        mapstraction.addControls({
            pan: true,
            zoom: 'small',
            map_type: true
        });
      });

    </script>
  <% end -%>
</head>
<body>

<h1><%=h @race %></h1>

<p>
	Pickford Hay Days • <%= @race.date ? @race.date.strftime("%B %e, %Y") : @race.year %>
</p>

<%= yield %>

</body>
</html>

app/views/layouts/reports.txt.erb
<%= @race.name %>
Pickford Hay Days • <%= @race.date ? @race.date.strftime("%B %e, %Y") : @race.year %>

<%= yield %>